name: Publish LiveTL.Common.Lib

on:
  push:
    branches:
      - master
    paths:
      - dotnet/Common.Lib/**

jobs:
  publish: 
    name: Publish LiveTL.Common.Lib to Nuget
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with: 
          PROJECT_FILE_PATH: dotnet/Common.Lib/LiveTL.Common.Lib.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # INCLUDE_SYMBOLS: true
