name: Publish @livetl/ui-components

on:
  push:
    branches:
      - master
    paths:
      - javascript/ui-components/**
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish @livetl/ui-components to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: |
          cd javascript/ui-components
          cd submodules/LiveTL
          npm run update:list
          cd ../..
          cp -r submodules/LiveTL/src build
          # cp -r submodules/LiveTL/theme build/theme
          cd build
          rm -rf manifest.json empty.html __tests__ plugins
          cd ..
          mkdir build/plugins
          mkdir build/meta
          cp -r submodules/LiveTL/src/plugins/*.json build/plugins 
          cp submodules/LiveTL/postcss.config.js build/meta/postcss.config.js
          cp submodules/LiveTL/tailwind.config.js build/meta/tailwind.config.js
          node utils/package.js
          npm publish build --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
