name: Publish @livetl/ui-components

on:
  push:
    branches:
      - master
    paths:
      - ui-components/**

jobs:
  publish-npm:
    name: Publish @livetl/ui-components to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: |
          cd ui-components
          cp -r submodules/LiveTL/src build
          cd build
          rm -rf manifest.json empty.html submodules __tests__ plugins
          cd ..
          node utils/package.js
          npm publish build --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
